---
title: "Analisis Estadistico"
output: html_notebook
---

```{r}
library(dplyr)
library(tidyr) 
library(readr) 
library(udunits2)
library(tidyverse)
library(car)
library(agricolae)
library(tidyverse)
library(ggplot2)
library(patchwork)
library(RColorBrewer)
library(ggbreak)
library(plotrix)
library(ggsignif)
library(paletteer)
```

```{r}
Quitosano <- read.csv("~/CursoR/CursoRgit/Materiales/nebiol_quitosano.csv")
Nebiol <- read.csv("~/CursoR/CursoRgit/Materiales/Nebiol.csv")

par(mfrow=c(1,2))
hist(Nebiol$Longitud)
qqnorm(Nebiol$Longitud)

# Shapiro-Wilk normality test
shapiro.test(Nebiol$Longitud)

# Normalizar
par(mfrow=c(1,2))
hist(sqrt(Nebiol$Longitud))
qqnorm(sqrt(Nebiol$Longitud))

# Shapiro-Wilk normality test
shapiro.test(sqrt(Nebiol$Longitud))


# Checar si estan balanceados
Nebiol %>%
  group_by(Tratamiento)%>%
  summarise(n())
```

## Graficos de l promedio de la longitud de raiz
```{r}
# Filtrar datos para solo obtener una tabla de los promedios de la longitud de raiz 

# Nebiol
Nebiol_prom <- Nebiol %>%
  filter(!is.na(Longitud)) %>%
  group_by(Tratamiento) %>%
  summarize(Media_longitud_raiz= mean(Longitud, na.rm = TRUE),
            Desv_est = sd(Longitud, na.rm = TRUE),
            Error_desv_est = std.error(Longitud, na.rm = TRUE))

levels(Nebiol_prom$Tratamiento)
Nebiol_prom$Tratamiento=factor(Nebiol_prom$Tratamiento,levels=c("Control","NAA","GA3","N1 250 uL", "N1 1:10", "N1 1:20", "N1 1:50", "N2 250 uL filt", "N2 250 uL directo", "N3 1:10", "N3 1:20", "N3 1:50"))
levels(Nebiol_prom$Tratamiento)


graflongitud_n <- ggplot(Nebiol_prom)+
  theme_classic()+
  geom_col(aes(x = Tratamiento, y = Media_longitud_raiz, fill=Tratamiento))+
  ggtitle("Bioensayo de muestras de Nebiol")+
  theme(plot.title = element_text(hjust = 0.5, size = 15, color = "black", face = "bold"))+
  ylab("Longitud de raíz")+
  theme(axis.text.x = element_text(angle=45,hjust=1))+
  theme(axis.title.y=element_text(vjust = 3))+
  scale_fill_manual(values=c(rep("steelblue3",12)))+
  theme(legend.position = "none")
```


```{r}
# Quitosano
Quitosano_prom <- Quitosano %>%
  filter(!is.na(Longitud)) %>%
  group_by(Tratamiento) %>%
  summarize(Media_longitud_raiz= mean(Longitud, na.rm = TRUE),
            Desv_est = sd(Longitud, na.rm = TRUE),
            Error_desv_est = std.error(Longitud, na.rm = TRUE))

levels(Quitosano_prom$Tratamiento)
Quitosano_prom$Tratamiento=factor(Quitosano_prom$Tratamiento,levels=c("Control","NAA","GA3","M1 250 uL", "M1 1:10", "M1 1:20", "M2 250 uL", "M2 1:10", "M2 1:20", "M3 250 uL","M3 1:10", "M3 1:20", "M4 250 uL","M4 1:10", "M4 1:20"))
levels(Quitosano_prom$Tratamiento)

graflongitud_q <- ggplot(Quitosano_prom)+
  theme_classic()+
  geom_col(aes(x = Tratamiento, y = Media_longitud_raiz, fill=Tratamiento))+
  ggtitle("Bioensayo de muestras de Quitosano")+
  theme(plot.title = element_text(hjust = 0.5, size = 15, color = "black", face ="bold"))+
  ylab("Longitud de raíz")+
  theme(axis.text.x = element_text(angle=45,hjust=1))+
  theme(axis.title.y=element_text(vjust = 3))+
  scale_fill_manual(values=c(rep("#2E8B57",15)))+
  theme(legend.position = "none")
```

```{r}
Nebiol_prom_lat <- Nebiol %>%
  filter(!is.na(Laterales)) %>%
  group_by(Tratamiento) %>%
  summarize(Media_laterales= mean(Laterales, na.rm = TRUE),
            Desv_est_lat = sd(Laterales, na.rm = TRUE),
            Error_desv_est_lat = std.error(Laterales, na.rm = TRUE))

Nebiol_tabla <- cbind(Nebiol_prom,Nebiol_prom_lat[,-c(1)])

graflaterales_n <- ggplot(Nebiol_tabla)+
  theme_classic()+
  geom_col(aes(y = Media_laterales, x = Tratamiento, fill= Tratamiento))+
  ggtitle("Bioensayo de muestras de Nebiol")+
  theme(plot.title = element_text(hjust = 0.5, size = 15, color = "black", face = "bold"))+
  theme(axis.text.x = element_text(angle=45,hjust=1))+
  ylab("Raíces laterales")+
  scale_fill_manual(values=c(rep("steelblue3",12)))+
  theme(legend.position = "none")

graflongitud_n|graflaterales_n
```


```{r}
Quitosano_prom_lat <- Quitosano %>%
  filter(!is.na(Laterales)) %>%
  group_by(Tratamiento) %>%
  summarize(Media_laterales= mean(Laterales, na.rm = TRUE),
            Desv_est_lat = sd(Laterales, na.rm = TRUE),
            Error_desv_est_lat = std.error(Laterales, na.rm = TRUE))

Quitosano_tabla <- cbind(Quitosano_prom,Quitosano_prom_lat[,-c(1)])

graflaterales_q <- ggplot(Quitosano_tabla)+
  theme_classic()+
  geom_col(aes(y = Media_laterales, x = Tratamiento, fill= Tratamiento))+
  ggtitle("Bioensayo de muestras de Nebiol")+
  theme(plot.title = element_text(hjust = 0.5, size = 15, color = "black", face = "bold"))+
  theme(axis.text.x = element_text(angle=45,hjust=1))+
  ylab("Raíces laterales")+
  scale_fill_manual(values=c(rep("#2E8B57",15)))+
  theme(legend.position = "none")

graflongitud_q|graflaterales_q
```

