---
title: "Analisis Estadistico"
output: html_notebook
---

```{r}
# Librerias
library(dplyr)
library(tidyr) 
library(readr) 
library(udunits2)
library(tidyverse)
library(car)
library(agricolae)
library(tidyverse)
library(ggplot2)
library(patchwork)
library(RColorBrewer)
library(ggbreak)
library(plotrix)
library(ggsignif)
library(paletteer)

# DATA
Quitosano2 <- read.csv("~/CursoR/CursoRgit/Agronomia/Materiales/Quitosano_lateral_long.csv")
Quitosano3 <- read.csv("~/CursoR/CursoRgit/Agronomia/Materiales/Quitosano_promedios.csv")
Quitosano <- read.csv("~/CursoR/CursoRgit/Agronomia/Materiales/Quitosano.csv")
Nebiol <- read.csv("~/CursoR/CursoRgit/Agronomia/Materiales/Nebiol.csv")
```

# NEBIOL

### Análisis para la variable longitud de raíz:
```{r}
par(mfrow=c(1,2))
hist(Nebiol$Longitud)
qqnorm(Nebiol$Longitud)

# Shapiro-Wilk normality test
shapiro.test(Nebiol$Longitud)

# Normalizar
par(mfrow=c(1,2))
hist(sqrt(Nebiol$Longitud))
qqnorm(sqrt(Nebiol$Longitud))

# Shapiro-Wilk normality test
shapiro.test(sqrt(Nebiol$Longitud)) # no se puede normalizar por lo que se debe anamilizar con un test no parametrico

# Checar si estan balanceados
Nebiol %>%
  group_by(Tratamiento)%>% 
  summarise(n())

kruskal.test(Longitud ~ Tratamiento, data = Nebiol) # p value es menor a 0.05, por que si hay diferencias significativas entre los tratamientos

pairwise.wilcox.test(Nebiol$Longitud,
                     Nebiol$Tratamiento,
                     p.adjust.method = "bonferroni")
```

### Análisis para la variable raíces laterales:
```{r}
par(mfrow=c(1,2))
hist(Nebiol$Laterales)
qqnorm(Nebiol$Laterales)

# Shapiro-Wilk normality test
shapiro.test(Nebiol$Laterales)

# Normalizar
par(mfrow=c(1,2))
hist(sqrt(Nebiol$Laterales+1))
qqnorm(sqrt(Nebiol$Laterales+1))

# Shapiro-Wilk normality test
shapiro.test(sqrt(Nebiol$Laterales+1)) # no se puede normalizar por lo que se debe analizar por un test no parametrico

kruskal.test(Laterales ~ Tratamiento, data= Nebiol) # pvalue es menor a 0.05 por lo que si ha diferencias significativas entre los tratamientos

pairwise.wilcox.test(Nebiol$Laterales,
                     Nebiol$Tratamiento,
                     p.adjust.method = "bonferroni")
```

# QUITOSANO

### Análisis para la variable longitud de raíz:
```{r}
par(mfrow=c(1,2))
hist(Quitosano$Longitud)
qqnorm(Quitosano$Longitud)

# Shapiro-Wilk normality test
shapiro.test(Quitosano$Longitud)

# Normalizar
par(mfrow=c(1,2))
hist(sqrt(Quitosano$Longitud))
qqnorm(sqrt(Quitosano$Longitud))

shapiro.test(log(Quitosano$Longitud)) # no se puede normalizar por lo que se debe analizar con un test no parametrico

kruskal.test(Longitud ~ Tratamiento, data = Quitosano) # pvalue es menor a 0.05 por lo que si existen diferencias entre los tratamientos

pairwise.wilcox.test(Quitosano$Longitud,
                     Quitosano$Tratamiento,
                     p.adjust.method = "bonferroni")

```

### Análisis para la variable de raíces laterales:
```{r}
par(mfrow=c(1,2))
hist(Quitosano$Laterales)
qqnorm(Quitosano$Laterales)

shapiro.test(Quitosano$Laterales)

# Normalizar
par(mfrow=c(1,2))
hist(sqrt(Quitosano$Laterales+1))
qqnorm(sqrt(Quitosano$Laterales+1))

shapiro.test(log(Quitosano$Laterales+1)) # No se puede normalizar por lo que se debe analizar con un test no parametrico

kruskal.test(Laterales ~ Tratamiento, data = Quitosano) # pvalue es menor a 0.05 por lo que si existen diferencias significativas entre los tratamientos

pairwise.wilcox.test(Quitosano$Laterales,
                     Quitosano$Laterales,
                     p.adjust.method = "bonferroni")
```


## Graficos del promedio de la longitud de raiz y raices laterales para Nebiol
```{r}

# Filtrar datos para solo obtener una tabla de los promedios de la longitud de raiz:
Nebiol_prom <- Nebiol %>%
  filter(!is.na(Longitud)) %>%
  group_by(Tratamiento) %>%
  summarize(Media_longitud_raiz= mean(Longitud, na.rm = TRUE),
            Desv_est = sd(Longitud, na.rm = TRUE),
            Error_desv_est = std.error(Longitud, na.rm = TRUE))


# Filtrar datos para solo obtener una tabla de los promedios de las raices laterales:
Nebiol_prom_lat <- Nebiol %>%
  filter(!is.na(Laterales)) %>%
  group_by(Tratamiento) %>%
  summarize(Media_laterales= mean(Laterales, na.rm = TRUE),
            Desv_est_lat = sd(Laterales, na.rm = TRUE),
            Error_desv_est_lat = std.error(Laterales, na.rm = TRUE))

# Se unen las tablas
Nebiol_tabla <- cbind(Nebiol_prom,Nebiol_prom_lat[,-c(1)])

# Se acomodan los datos
levels(Nebiol_tabla$Tratamiento)
Nebiol_tabla$Tratamiento=factor(Nebiol_tabla$Tratamiento,levels=c("Control","NAA","GA3","N1 250 uL", "N1 1:10", "N1 1:20", "N1 1:50", "N2 250 uL filt", "N2 250 uL directo", "N3 1:10", "N3 1:20", "N3 1:50"))
levels(Nebiol_tabla$Tratamiento)

# Se grafican los promedios de la longitud de raiz y las raices laterales
ggplot(Nebiol_tabla)+
  theme_classic()+
  geom_col(aes(x = Tratamiento, y = Media_longitud_raiz, fill=Tratamiento))+
  ggtitle("Bioensayo de muestras de Nebiol")+
  theme(plot.title = element_text(hjust = 0.5, size = 15, color = "black", face = "bold"))+
  ylab("Longitud de raíz")+
  theme(axis.text.x = element_text(angle=45,hjust=1))+
  theme(axis.title.y=element_text(vjust = 3))+
  scale_fill_manual(values=c("#6551CC","#8F7EE5","#BFB2FF", "#7EC3E5", "#7EC3E5", "#7EC3E5","#7EC3E5", "#0F6B99","#0F6B99","#6B990F" ,"#6B990F","#6B990F"))
  theme(legend.position = "none")

ggplot(Nebiol_tabla)+
  theme_classic()+
  geom_col(aes(y = Media_laterales, x = Tratamiento, fill= Tratamiento))+
  ggtitle("Bioensayo de muestras de Nebiol")+
  theme(plot.title = element_text(hjust = 0.5, size = 15, color = "black", face = "bold"))+
  theme(plot.caption = element_text(color = "red", hjust = 0, vjust = -2, size = 12))+
  labs(caption = "*No se realizó conteo de raíces laterales del tratamiento NAA por alta abundanica.")+
  theme(axis.text.x = element_text(angle=45,hjust=1))+
  ylab("Raíces laterales")+
  scale_fill_manual(values=c("#6551CC","#8F7EE5","#BFB2FF", "#7EC3E5", "#7EC3E5", "#7EC3E5","#7EC3E5", "#0F6B99","#0F6B99","#6B990F" ,"#6B990F","#6B990F"))+ 
  theme(legend.position = "none")

# Nebiol_tabla <- Nebiol_tabla[-c(12),] se utiliza para eliminar la fila del tratamiento NAA para que no se muestre en a tabla debido a que no se contaron las raíces laterales de NAA por su alta abundancia.
```

## Graficos del promedio de la longitud de raiz y raices laterales para Quitosano
```{r}
# Filtrar datos para solo obtener una tabla de los promedios de la longitud de raiz:
Quitosano_prom <- Quitosano %>%
  filter(!is.na(Longitud)) %>%
  group_by(Tratamiento) %>%
  summarize(Media_longitud_raiz= mean(Longitud, na.rm = TRUE),
            Desv_est = sd(Longitud, na.rm = TRUE),
            Error_desv_est = std.error(Longitud, na.rm = TRUE))

# Filtrar datos para solo obtener una tabla de los promedios de las raices laterales:
Quitosano_prom_lat <- Quitosano %>%
  filter(!is.na(Laterales)) %>%
  group_by(Tratamiento) %>%
  summarize(Media_laterales= mean(Laterales, na.rm = TRUE),
            Desv_est_lat = sd(Laterales, na.rm = TRUE),
            Error_desv_est_lat = std.error(Laterales, na.rm = TRUE))

# Se unen las tablas:
Quitosano_tabla <- cbind(Quitosano_prom,Quitosano_prom_lat[,-c(1)])

# Se acomodan los datos:
levels(Quitosano_tabla$Tratamiento)
Quitosano_tabla$Tratamiento=factor(Quitosano_tabla$Tratamiento,levels=c("Control","NAA","GA3","M1 250 uL", "M1 1:10", "M1 1:20", "M2 250 uL", "M2 1:10", "M2 1:20", "M3 250 uL","M3 1:10", "M3 1:20", "M4 250 uL","M4 1:10", "M4 1:20"))
levels(Quitosano_tabla$Tratamiento)

# Se grafican los promedios de la longitud de raiz y las raices laterales:
ggplot(Quitosano_tabla)+
  theme_classic()+
  geom_col(aes(x = Tratamiento, y = Media_longitud_raiz, fill=Tratamiento))+
  ggtitle("Bioensayo de muestras de Quitosano")+
  theme(plot.title = element_text(hjust = 0.5, size = 15, color = "black", face ="bold"))+
  ylab("Longitud de raíz")+
  theme(axis.text.x = element_text(angle=45,hjust=1))+
  theme(axis.title.y=element_text(vjust = 3))+
  scale_fill_manual(values=c("#6551CC","#8F7EE5","#BFB2FF", "#7EC3E5", "#7EC3E5", "#7EC3E5","#0F6B99", "#0F6B99","#0F6B99","#C3E57E", "#C3E57E", "#C3E57E" ,"#6B990F","#6B990F","#6B990F"))+ 
  theme(legend.position = "none")

ggplot(Quitosano_tabla)+
  theme_classic()+
  geom_col(aes(y = Media_laterales, x = Tratamiento, fill= Tratamiento))+
  ggtitle("Bioensayo de muestras de Quitosano")+
  theme(plot.title = element_text(hjust = 0.5, size = 15, color = "black", face = "bold"))+
  theme(plot.caption = element_text(color = "red", hjust = 0, vjust=-2, size = 12))+
  theme(axis.text.x = element_text(angle=45,hjust=1, size=8))+
  ylab("Raíces laterales")+
  scale_fill_manual(values=c("#6551CC","#8F7EE5","#BFB2FF", "#7EC3E5", "#7EC3E5", "#7EC3E5","#0F6B99", "#0F6B99","#0F6B99","#C3E57E", "#C3E57E", "#C3E57E" ,"#6B990F","#6B990F","#6B990F"))+
  theme(legend.position = "none")+
  labs(caption="*No se realizó conteo de raíces laterales del tratamiento NAA por alta abundancia.")
  
# Quitosano_tabla <- Quitosano_tabla[-c(15),] para eliminar la fila correspondiente al tratamiento NAA, ya que no se contaron las raíces laterales debido a una alta abundancia
```

```{r}
ggplot(Quitosano_tabla, aes(x= Tratamiento, y = Media_longitud_raiz, fill=Tratamiento, group=1))+
  theme_classic()+
  geom_col(aes(y = Media_longitud_raiz, x = Tratamiento, fill= Tratamiento))+
  ggtitle("Bioensayo de muestras de Quitosano")+
  theme(plot.title = element_text(hjust = 0.5, size = 15, color = "black", face ="bold"))+
  ylab("Longitud de raíz")+
  theme(axis.text.x = element_text(angle=45,hjust=1))+
  theme(axis.title.y=element_text(vjust = 3))+
  scale_fill_manual(values=c(rep("#2E8B57",15)))+
  theme(legend.position = "none")+
  geom_line(aes(y=Media_laterales))+
  theme(axis.text.y=element_text(vjust = 3))+
  geom_text(aes(label = (Media_laterales)))


# Grafico donde se incluyan ambas variables de longitud y laterales
ggplot(Quitosano3,aes(x=Tratamiento, y = Resultado,fill= Tipo))+ 
  theme_bw()+
  geom_bar(stat= "summary", fun="mean", position="dodge")+
  scale_fill_discrete(name = "Tipo de variable", 
                      labels = c("Promedio raíces laterales", "Promedio longitud de raíz"))+ 
  theme(axis.title.y = element_blank())+
  theme(axis.text.x = element_text(angle=45,hjust=1))+
  scale_x_discrete(limits = c("Control","NAA","GA3","M1 250 uL", "M1 1:10","M1 1:20","M2 250 uL", "M2 1:10","M2 1:20","M3 250 uL","M3 1:10","M3 1:20", "M4 250 uL","M4 1:10","M4 1:20"))+
  scale_fill_manual(name = "Tipo de variable", values = c("#6B990F", "#6551CC"))+
  geom_text(aes(label = Resultado))

```
