---
title: "Bioensayo ABX1"
output: html_notebook
---

```{r}
# Librerias:

library(dplyr)
library(tidyr) 
library(readr) 
library(udunits2)
library(tidyverse)
library(car)
library(agricolae)
library(ggplot2)
library(patchwork)
library(RColorBrewer)
library(ggbreak)
library(plotrix)
library(ggsignif)
library(paletteer)
library(reshape2) 

# DATA:

ABX <- read.csv("~/CursoR/CursoRgit/Agronomia/Materiales/Bioensayo ABX1.csv")
```

### Graficos del promedio de la longitud de raíz y laterales
```{r}
# Filtrar datos para solo obtener una tabla de los promedios de la longitud de raiz y de las raíces laterales:

Prom_long <- ABX %>%
  group_by(Tratamiento) %>%
  summarize(Long_lote1 = mean(Longitud_L1, na.rm = TRUE),
            Long_lote2 = mean(Longitud_L2, na.rm = TRUE))

Prom_lat <- ABX %>%
  group_by(Tratamiento) %>%
  summarize(Lat_lote1 = mean(ifelse(Laterales_L1 == 0, NA, Laterales_L1), na.rm = TRUE),
            Lat_lote2 = mean(ifelse(Laterales_L2 == 0, NA, Laterales_L2), na.rm = TRUE))

# Se acomodan los datos:
levels(Prom_long$Tratamiento)
Prom_long$Tratamiento = factor(Prom_long$Tratamiento, levels = c("Control", "NAA", "GA3", "Exuroot Directo", "Exuroot 1:20", "Exuroot 1:50", "ABX1 7 µM", "ABX1 14 µM", "ABX1 28 µM"))
levels(Prom_long$Tratamiento)

levels(Prom_lat$Tratamiento)
Prom_lat$Tratamiento = factor(Prom_lat$Tratamiento, levels = c("Control", "NAA", "GA3","Exuroot Directo", "Exuroot 1:20", "Exuroot 1:50","ABX1 7 µM", "ABX1 14 µM", "ABX1 28 µM"))
levels(Prom_lat$Tratamiento)

# Gráfico longitud de raíz lote 1:
g1 <- ggplot(Prom_long)+
  theme_classic()+
  geom_col(aes(x = Tratamiento, y = Long_lote1, fill = Tratamiento))+
  ggtitle("Bioensayo ABX-1 L1 (14Mayo24)")+
  theme(plot.title = element_text(hjust = 0.5, size = 15, color = "black", face = "bold"))+
  ylab("Longitud raíz primaria")+
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 13))+
  theme(axis.text.y = element_text(size = 13))+
  theme(axis.title.x = element_text(size = 15))+
  theme(axis.title.y = element_text(size = 15, vjust = 3))+
  scale_fill_manual(values = c("#BFB2FF", "#8F7EE5", "#6559CC", "#0F6B99", "#0F6B99", "#0F6B99", "#A3CC51", "#A3CC51", "#A3CC51"))+
  theme(legend.position = "none")+
  ylim(0,45)

# Gráfico raíces laterales lote 1:
g2 <- ggplot(Prom_lat)+
  theme_classic()+
  geom_col(aes(x = Tratamiento, y = Lat_lote1, fill = Tratamiento))+
  ggtitle("Bioensayo ABX-1 L1 (14Mayo24)")+
  theme(plot.title = element_text(hjust = 0.5, size = 15, color = "black", face = "bold"))+
  ylab("Raíces laterales")+
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 13))+
  theme(axis.text.y = element_text(size = 13))+
  theme(axis.title.x = element_text(size = 15))+
  theme(axis.title.y = element_text(size = 15, vjust = 3))+
  scale_fill_manual(values = c("#BFB2FF", "#8F7EE5", "#6559CC", "#0F6B99", "#0F6B99", "#0F6B99", "#A3CC51", "#A3CC51", "#A3CC51"))+
  theme(legend.position = "none")+
  ylim(0,20)

# Gráfico longitud de raíz lote 2:
g3 <- ggplot(Prom_long)+
  theme_classic()+
  geom_col(aes(x = Tratamiento, y = Long_lote2, fill = Tratamiento))+
  ggtitle("Bioensayo ABX-1 L2 (21Mayo24)")+
  theme(plot.title = element_text(hjust = 0.5, size = 15, color = "black", face = "bold"))+
  ylab("")+
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 13))+
  theme(axis.text.y = element_text(size = 13))+
  theme(axis.title.x = element_text(size = 15))+
  theme(axis.title.y = element_text(size = 15, vjust = 3))+
  scale_fill_manual(values = c("#BFB2FF", "#8F7EE5", "#6559CC", "#0F6B99", "#0F6B99", "#0F6B99", "#A3CC51", "#A3CC51", "#A3CC51"))+
  theme(legend.position = "none")+
  ylim(0,45)

# Gráfico raíces laterales lote 2:
g4 <- ggplot(Prom_lat)+
  theme_classic()+
  geom_col(aes(x = Tratamiento, y = Lat_lote2, fill = Tratamiento))+
  ggtitle("Bioensayo ABX-1 L2 (21Mayo24)")+
  theme(plot.title = element_text(hjust = 0.5, size = 15, color = "black", face = "bold"))+
  ylab("")+
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 13))+
  theme(axis.text.y = element_text(size = 13))+
  theme(axis.title.x = element_text(size = 15))+
  theme(axis.title.y = element_text(size = 15, vjust = 3))+
  scale_fill_manual(values = c("#BFB2FF", "#8F7EE5", "#6559CC", "#0F6B99", "#0F6B99", "#0F6B99", "#A3CC51", "#A3CC51", "#A3CC51"))+
  theme(legend.position = "none")+
  ylim(0,20)
```




