---
title: "F3 Maduro y Sin Madurar"
output: html_notebook
---

```{r}
# Librerias:

library(dplyr)
library(tidyr) 
library(readr) 
library(udunits2)
library(tidyverse)
library(car)
library(agricolae)
library(ggplot2)
library(patchwork)
library(RColorBrewer)
library(ggbreak)
library(plotrix)
library(ggsignif)
library(paletteer)

# DATA:

Muestras <- read.csv("~/CursoR/CursoRgit/Agronomia/Materiales/F3.csv")
```

```{r}
### Graficos del promedio de la longitud de raiz y raices laterales

# Filtrar datos para solo obtener una tabla de los promedios de la longitud de raiz y de las raíces laterales:

Promedios <- Muestras %>%
  group_by(Tratamiento) %>%
  summarize(Long_lote1 = mean(Longitud, na.rm = TRUE),
            Lat_Lote1 = mean(ifelse(Laterales == 0, NA, Laterales),
                             na.rm = TRUE))

# Se acomodan los datos:

levels(Promedios$Tratamiento)
Promedios$Tratamiento=factor(Promedios$Tratamiento, levels=c("Control", "NAA", "GA3", "F3M directo", "F3M 1:20", "F3M 1:50", "F3S directo", "F3S 1:20", "F3S 1:50"))
levels(Promedios$Tratamiento)

# Grafico de la longitud de raíz lote 1:
ggplot(Promedios)+
  theme_classic()+
  geom_col(aes(x = Tratamiento, y = Long_lote1, fill = Tratamiento))+
  ggtitle("Bioensayo de F3 Maduro y Sin Madurar")+
  theme(plot.title = element_text(hjust = 0.5, size = 15, color = "black", face = "bold"))+
  ylab("Longitud de raíz primaria")+
  theme(axis.text.x = element_text(size = 13, angle = 45, hjust = 1))+
  theme(axis.text.y = element_text(size = 13))+
  theme(axis.title.x = element_text(size = 15))+
  theme(axis.title.y = element_text(size = 15, vjust = 3))+
  scale_fill_manual(values = c("#BFB2FF", "#8F7EE5", "#422CB2", "#51A3CC", "#51A3CC","#51A3CC", "#A3CC51", "#A3CC51", "#A3CC51"))+
  theme(legend.position = "none")


```

