---
title: "Muestras externas Humik y Exuroot"
output: html_notebook
---

```{r}
# Librerias
library(dplyr)
library(tidyr) 
library(readr) 
library(udunits2)
library(tidyverse)
library(car)
library(agricolae)
library(ggplot2)
library(patchwork)
library(RColorBrewer)
library(ggbreak)
library(plotrix)
library(ggsignif)
library(paletteer)
library(reshape2)

# DATA

Bioensayo <- read.csv("~/CursoR/CursoRgit/Agronomia/Materiales/Bioensayo muestras externas_humik.csv")

Laterales <- read.csv("~/CursoR/CursoRgit/")
```

### Graficos del promedio de la longitud de raiz y raices laterales 

```{r}
# Filtrar datos para solo obtener una tabla de los promedios de la longitud de raiz para los tres lotes:

Prom_long <- Bioensayo %>%
  group_by(Tratamiento) %>%
  summarize(Long_L1 = mean(Longitud_Lote1, na.rm = TRUE),
            Long_L2 = mean(Longitud_Lote2, na.rm = TRUE),
            Long_L3 = mean(Longitud_Lote3, na.rm = TRUE))


Prom_lat <- Bioensayo %>%
  group_by(Tratamiento) %>%
  summarize(Lat_L1 = mean(ifelse(Laterales_Lote1 == 0, NA, Laterales_Lote1), na.rm = TRUE),
            Lat_L2 = mean(ifelse(Laterales_Lote2 == 0, NA, Laterales_Lote2), na.rm = TRUE),
            Lat_L3 = mean(ifelse(Laterales_Lote3 == 0, NA, Laterales_Lote3), na.rm = TRUE))

Prom <- Bioensayo %>%
  group_by(Tratamiento) %>%
  summarize(Long_L1 = mean(Longitud_Lote1, na.rm = TRUE),
            Lat_L1 = mean(ifelse(Laterales_Lote1==0, NA, Laterales_Lote1), na.rm = TRUE),
            Long_L2 = mean(Longitud_Lote2, na.rm = TRUE),
            Lat_L2 = mean(ifelse(Laterales_Lote2==0, NA, Laterales_Lote2), na.rm = TRUE),
            Long_L3 = mean(Longitud_Lote3, na.rm = TRUE),
            Lat_L3 = mean(ifelse(Laterales_Lote3==0, NA, Laterales_Lote3), na.rm = TRUE))

# Se acomodan los datos:
levels(Prom_long$Tratamiento)
Prom_long$Tratamiento = factor(Prom_long$Tratamiento, levels = c("Control", "NAA", "GA3", "Humik-WSG directo", "Humik-WSG 1:20", "Humik-WSG 1:50", "Humik-WSP directo", "Humik-WSP 1:20", "Humik-WSP 1:50", "Humik-ONE directo", "Humik-ONE 1:20", "Humik-ONE 1:50", "Ful-Grow Gold 2x directo", "Ful-Grow Gold 2x 1:20", "Ful-Grow Gold 2x 1:50", "Exuroot+ECCA M directo", "Exuroot+ECCA M 1:20", "Exuroot+ECCA M 1:50", "Exuroot+ECCA S/M directo", "Exuroot+ECCA S/M 1:20", "Exuroot+ECCA S/M 1:50"))
levels(Prom_long$Tratamiento)

levels(Prom_lat$Tratamiento)
Prom_lat$Tratamiento = factor(Prom_lat$Tratamiento, levels = c("Control","NAA","GA3","Humik-WSG directo","Humik-WSG 1:20","Humik-WSG 1:50","Humik-WSP directo","Humik-WSP 1:20","Humik-WSP 1:50","Humik-ONE directo","Humik-ONE 1:20","Humik-ONE 1:50","Ful-Grow Gold 2x directo","Ful-Grow Gold 2x 1:20","Ful-Grow Gold 2x 1:50","Exuroot+ECCA M directo","Exuroot+ECCA M 1:20","Exuroot+ECCA M 1:50","Exuroot+ECCA S/M directo","Exuroot+ECCA S/M 1:20","Exuroot+ECCA S/M 1:50"))
levels(Prom_lat$Tratamiento)

# Grafico de la longitud de raíz L1:

g1 <-  ggplot(Promedios)+
  theme_classic()+
  geom_col(aes(x = Tratamiento, y = Long_L1, fill= Tratamiento))+
  ggtitle("Bioensayo muestras externas Humik y Exuroot+ECCA'S L1 (15Feb24)")+
  theme(plot.title = element_text(hjust = 0.5, size = 18, color = "black", face = "bold"))+
  ylab("Longitud de raíz primaria")+
  theme(axis.text.x = element_text(angle=45,hjust=1, size = 9))+
  theme(axis.text.y = element_text(size = 9))+
  theme(axis.title.x = element_text(size = 15))+
  theme(axis.title.y = element_text(vjust = 3, size = 15))+
  scale_fill_manual(values=c("#BFB2FF","#8F7EE5","#6559CC","#260F99", "#260F99","#260F99","#0F6B99", "#0F6B99","#0F6B99", "#7EC3E5", "#7EC3E5", "#7EC3E5","#6B990F","#6B990F","#6B990F","#A3CC51" ,"#A3CC51","#A3CC51", "#C3E58E", "#C3E58E", "#C3E58E"))+
  ylim(0,50)+
  theme(legend.position = "none")

# Grafico raices laterales L1:
g2 <- ggplot(Promedios)+
  theme_classic()+
  geom_col(aes(x = Tratamiento, y = Lat_L1, fill=Tratamiento))+
  ggtitle("Bioensayo muestras externas Humik y Exuroot+ECCA'S L1 (15Feb24)")+
  theme(plot.title = element_text(hjust = 0.5, size = 18, color = "black", face = "bold"))+
  ylab("Raíces laterales")+
  theme(axis.text.x = element_text(angle=45,hjust=1, size = 9))+
  theme(axis.text.y = element_text(size = 9))+
  theme(axis.title.y=element_text(vjust = 3, size = 15))+
  theme(axis.title.x = element_text(size = 15))+
  scale_fill_manual(values=c("#BFB2FF","#8F7EE5","#6559CC","#260F99", "#260F99","#260F99","#0F6B99", "#0F6B99","#0F6B99", "#7EC3E5", "#7EC3E5", "#7EC3E5","#6B990F","#6B990F","#6B990F","#A3CC51" ,"#A3CC51","#A3CC51", "#C3E58E", "#C3E58E", "#C3E58E"))+
  ylim(0,25)+
  theme(legend.position = "none")

# Grafico de la longitud de raíz L2:
g3 <- ggplot(Promedios)+
  theme_classic()+
  geom_col(aes(x = Tratamiento, y = Long_L2, fill= Tratamiento))+
  ggtitle("Bioensayo muestras externas Humik y Exuroot+ECCA'S L2 (05Marzo24)")+
  theme(plot.title = element_text(hjust = 0.5, size = 18, color = "black", face = "bold"))+
  ylab("Longitud raíz primaria")+
  theme(axis.text.x = element_text(angle=45,hjust=1, size = 9))+
  theme(axis.text.y = element_text(size = 9))+
  theme(axis.title.x = element_text(size = 15))+
  theme(axis.title.y = element_text(vjust = 3, size = 15))+
  scale_fill_manual(values=c("#BFB2FF","#8F7EE5","#6559CC","#260F99", "#260F99","#260F99","#0F6B99", "#0F6B99","#0F6B99", "#7EC3E5", "#7EC3E5", "#7EC3E5","#6B990F","#6B990F","#6B990F","#A3CC51" ,"#A3CC51","#A3CC51", "#C3E58E", "#C3E58E", "#C3E58E"))+
  ylim(0,50)+
  theme(legend.position = "none")

# Grafico raices laterales L2:
g4 <- ggplot(Promedios)+
  theme_classic()+
  geom_col(aes(x = Tratamiento, y = Lat_L2, fill=Tratamiento))+
  ggtitle("Bioensayo muestras externas Humik y Exuroot+ECCA'S L2 (05Marzo24)")+
  theme(plot.title = element_text(hjust = 0.5, size = 18, color = "black", face = "bold"))+
  ylab("Raíces laterales")+
  theme(axis.text.x = element_text(angle=45,hjust=1, size = 9))+
  theme(axis.text.y = element_text(size = 9))+
  theme(axis.title.x = element_text(size = 15))+
  theme(axis.title.y = element_text(vjust = 3, size = 15))+
  scale_fill_manual(values=c("#BFB2FF","#8F7EE5","#6559CC","#260F99", "#260F99","#260F99","#0F6B99", "#0F6B99","#0F6B99", "#7EC3E5", "#7EC3E5", "#7EC3E5","#6B990F","#6B990F","#6B990F","#A3CC51" ,"#A3CC51","#A3CC51", "#C3E58E", "#C3E58E", "#C3E58E"))+
  ylim(0,25)+
  theme(legend.position = "none")

# Grafico de la longitud de raíz L3:

g5 <-  ggplot(Promedios)+
  theme_classic()+
  geom_col(aes(x = Tratamiento, y = Long_L3, fill= Tratamiento))+
  ggtitle("Bioensayo muestras externas Humik y Exuroot+ECCA'S L3 (15Marzo24)")+
  theme(plot.title = element_text(hjust = 0.5, size = 18, color = "black", face = "bold"))+
  ylab("Longitud raíz primaria")+
  theme(axis.text.x = element_text(angle=45,hjust=1, size = 9))+
  theme(axis.text.y = element_text(size = 9))+
  theme(axis.title.x = element_text(size = 13))+
  theme(axis.title.y = element_text(vjust = 3, size = 13))+
  scale_fill_manual(values=c("#BFB2FF","#8F7EE5","#6559CC","#260F99", "#260F99","#260F99","#0F6B99", "#0F6B99","#0F6B99", "#7EC3E5", "#7EC3E5", "#7EC3E5","#6B990F","#6B990F","#6B990F","#A3CC51" ,"#A3CC51","#A3CC51", "#C3E58E", "#C3E58E", "#C3E58E"))+
  ylim(0,50)+
   theme(legend.position = "none")

# Grafico raices laterales L3:
g6 <- ggplot(Promedios)+
  theme_classic()+
  geom_col(aes(x = Tratamiento, y = Lat_L3, fill=Tratamiento))+
  ggtitle("Bioensayo muestras externas Humik y Exuroot+ECCA'S L3 (15Marzo24)")+
  theme(plot.title = element_text(hjust = 0.5, size = 18, color = "black", face = "bold"))+
  ylab("Raíces laterales")+
  theme(axis.text.x = element_text(angle=45,hjust=1, size = 9))+
  theme(axis.text.y = element_text(size = 9))+
  theme(axis.title.y=element_text(vjust = 3, size = 15))+
  theme(axis.title.x = element_text(size = 15))+
  scale_fill_manual(values=c("#BFB2FF","#8F7EE5","#6559CC","#260F99", "#260F99","#260F99","#0F6B99", "#0F6B99","#0F6B99", "#7EC3E5", "#7EC3E5", "#7EC3E5","#6B990F","#6B990F","#6B990F","#A3CC51" ,"#A3CC51","#A3CC51", "#C3E58E", "#C3E58E", "#C3E58E"))+
  ylim(0,25)+
  theme(legend.position = "none")
```

```{r}
# Todos los lotes en un mismo gráfico para la variable de longitud:

Prom_long <- longitud %>%
  group_by(Tratamiento, Lote) %>%
  summarize(Longitud= mean(ifelse(Longitud==0, NA, Longitud), na.rm = TRUE))

melt_long <- melt(Prom_long, id = c("Tratamiento"))

ggplot(melt_long, aes(x = Tratamiento, y = value, fill = variable))+
  theme_bw()+
  geom_col(position = "dodge")+
  ggtitle("Bioensayo de muestras externas Humik y Exuroot+ECCA'S (Longitud raíz primaria)")+
  theme(plot.title = element_text(hjust = 0.5, size = 18, color= "black", face = "bold"))+
  scale_x_discrete(limits = c("Control","NAA","GA3","Humik-WSG directo", "Humik-WSG 1:20","Humik-WSG 1:50","Humik-WSP directo", "Humik-WSP 1:20","Humik-WSP 1:50","Humik-ONE directo","Humik-ONE 1:20","Humik-ONE 1:50", "Ful-Grow Gold 2x directo","Ful-Grow Gold 2x 1:20","Ful-Grow Gold 2x 1:50", "Exuroot+ECCA M directo", "Exuroot+ECCA M 1:20", "Exuroot+ECCA M 1:50", "Exuroot+ECCA S/M directo", "Exuroot+ECCA S/M 1:20", "Exuroot+ECCA S/M 1:50"))+
  theme(axis.text.x = element_text(angle=45,hjust=1, size = 13))+
  theme(axis.text.y = element_text(size = 13))+
  theme(axis.title.x = element_text(size = 15))+
  theme(axis.title.y = element_text(vjust = 3, size = 15))+
  scale_fill_manual(name = "Lote",
                    values = c("#260F99", "#7EC3E5", "#A3CC51"),
                    labels = c("Lote 1", "Lote 2", "Lote 3"))

# Lotes 1 y 2 en un mismo gráfico para la variable de laterales
Prom_lat <- laterales %>%
  group_by(Tratamiento, Lote) %>%
  summarize(Laterales= mean(ifelse(Laterales==0, NA, Laterales), na.rm = TRUE))

melt_lat <- melt(Prom_lat, id = c("Tratamiento"))

ggplot(melt_lat, aes(x = Tratamiento, y = value, fill = variable))+
  theme_bw()+
  geom_col(position = "dodge")+
  ggtitle("Bioensayo de muestras externas Humik y Exuroot+ECCA'S (Raíces laterales)")+
  theme(plot.title = element_text(hjust = 0.5, size = 18, color= "black", face = "bold"))+
  scale_x_discrete(limits = c("Control","NAA","GA3","Humik-WSG directo", "Humik-WSG 1:20","Humik-WSG 1:50","Humik-WSP directo", "Humik-WSP 1:20","Humik-WSP 1:50","Humik-ONE directo","Humik-ONE 1:20","Humik-ONE 1:50", "Ful-Grow Gold 2x directo","Ful-Grow Gold 2x 1:20","Ful-Grow Gold 2x 1:50", "Exuroot+ECCA M directo", "Exuroot+ECCA M 1:20", "Exuroot+ECCA M 1:50", "Exuroot+ECCA S/M directo", "Exuroot+ECCA S/M 1:20", "Exuroot+ECCA S/M 1:50"))+
  theme(axis.text.x = element_text(angle=45,hjust=1, size = 13))+
  theme(axis.text.y = element_text(size = 13))+
  theme(axis.title.x = element_text(size = 15))+
  theme(axis.title.y = element_text(vjust = 3, size = 15))+
  scale_fill_manual(name = "Lote",
                    values = c("#260F99", "#7EC3E5", "#A3CC51"),
                    labels = c("Lote 1", "Lote 2", "Lote 3"))
```
